version: '2.7'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 8084:80
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    ports:
      - 8085:8081
    depends_on:
      - postgres
    environment:
      - POSTGRES_URL=postgres
      - POSTGRES_PORT=5432

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - 8086:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
